### ISSUE TITLE
Show-> Cordon ohne Produkt Bild falsch plaziert.

### ISSUE THREAD

**Issue by MaDmaX1337** [LordSchirmer/Ilch2_Shop#15]
Unzwar wenn man ein Cordon auf ein Produkt setzt dieses über kein Bild verfügt. Wird das dann so angezeigt: [https://prnt.sc/EI9uy5rDG2jB](https://prnt.sc/EI9uy5rDG2jB)

**Comment by LordSchirmer** [comment]
Danke für die Info. Ich habe die Positionierung angepasst.

https://github.com/LordSchirmer/Ilch2_Shop/commit/f1d2d4e97b3ef546b85605677224632b2eeebb83
